# build terraform infrastructure
name: Build and Deploy Terraform Infrastructure
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7
    
      - name: Azure Login using Service Principal
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            auth-type: service_principal

      - name: Terraform Init
        run: terraform  init 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format
        run: terraform fmt -check
        
      - name: Terraform Plan
        run: terraform plan 

      - name: Terraform Apply
        if:  
        run: terraform apply -auto-approve 

      - name: Output Terraform State
        run: terraform output -json