# build terraform infrastructure
name: Build and Deploy Terraform Infrastructure
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TF_ENV: prod  # Change to 'dev' for development environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init .IAC/${{ env.TF_ENV }}

      - name: Terraform Plan
        run: terraform plan .IAC/${{ env.TF_ENV }}

      - name: Terraform Apply
        run: terraform apply -auto-approve .IAC/${{ env.TF_ENV }}

      - name: Output Terraform State
        run: terraform output -json .IAC/${{ env.TF_ENV }}